package examples

import (
	"fmt"
	"os"
	"strings"
	"text/template"

	"github.com/Shresht7/Scribe/scribe"
)

// ExampleTextDocument demonstrates how to create a text document.
func ExampleDocument_basic() {
	// Create a new document
	document := scribe.NewDocument()

	// Append some text nodes to the document
	document.AppendChild(
		scribe.Text("Hello, world!"),
		scribe.Text("This", "is", "a", "test", "document.").Join("---"),
	)

	// Print the document to the console
	fmt.Println(document)

	// Output:
	// Hello, world!
	// This---is---a---test---document.
}

// ExampleTextDocument demonstrates how to create a text document using a string builder.
func ExampleDocument_stringBuilder() {
	// Create a new document
	document := scribe.NewDocument()

	builder := new(strings.Builder)

	builder.WriteString("This is ")
	builder.WriteString("generated ")
	builder.WriteString("by a string builder!!!")

	// Append some text nodes to the document
	document.AppendChild(
		scribe.Text("Example: String Builder"),
		scribe.Text("\n---\n"),
		builder,
		scribe.Text("\n---\n"),
	)

	// Print the document to the console
	fmt.Println(document)

	// Output:
	// Example: String Builder
	//
	// ---
	//
	// This is generated by a string builder!!!
	//
	// ---
}

// ExampleTextDocument demonstrates how to create a text document using a string builder and templates.
func ExampleDocument_templates() {
	// Create a new document
	document := scribe.NewDocument()

	// Create a string builder
	builder := new(strings.Builder)

	// Create a template and execute it
	tmp := template.Must(template.New("test").Parse("This is {{.}}!!!"))
	tmp.Execute(builder, "generated by a string builder in a template")

	// Append some text nodes to the document
	document.AppendChild(
		scribe.Text("Example: String Builder + Templates"),
		builder,
	)

	// Print the document to the console
	fmt.Println(document)

	// Output:
	// Example: String Builder + Templates
	// This is generated by a string builder in a template!!!
}

// ExampleTextDocument demonstrates how to write a text document to a io.Writer.
func ExampleDocument_writeToStdout() {
	// Create a new document
	document := scribe.NewDocument()

	// Append some text nodes to the document
	document.AppendChild(
		scribe.Text("Example: Using io.Writer (os.Stdout)"),
	)

	// write the document to the writer
	fmt.Fprintln(os.Stdout, document)

	// Output:
	// Example: Using io.Writer (os.Stdout)
}
